---
- name: apache
  hosts: all
  tasks:
    - name: install apache ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == 'Ubuntu'

    - name: install apache centos
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == 'CentOS'
   

