---
- name: ubuntu
  hosts: ubuntu
  tasks:
    - name: install apache
      apt:
        name: apache2
        state: latest
- name: centos
  hosts: centos
  tasks:
    - name: install apache
      yum:
       name: httpd
       state: latest
   

