---
- name: Manage User Accounts
  hosts: all
  become: true
  gather_facts: false
  tasks:
     - name: Create user
       user:
         name: ansible  
         shell: /bin/bash
         state: present
...
