---
- name: multiple user
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: create multiple user
      user:
        name: "{{ item }}"
      loop:
        - petu
        - barry
        - strinky
        

