---
- name: Create Users with Password
  hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Create user account with encrypted password
    user:
      name: "{{ user_name }}"
      password: " {{ 'Password1' | password_hash('sha512','AS343') }}"
      update_password: on_create
    when: user_create == 'yes'
  - name: Delete user account 
    user:
      name: "{{ user_name }}"
      state: 'absent'
      remove: true
    when: user_create == 'no'

